import breeze from 'breeze';
import AutoGeneratedKeyType from 'breeze';
import settings from '../settings';

export class DataService {

  serviceName = settings.serviceName;
  manager = new breeze.EntityManager(this.serviceName);

  getMasks() {
    var query = breeze.EntityQuery.from("Masks");
    return this.manager.executeQuery(query);
  }

  getProducts() {
    var query = breeze.EntityQuery.from("ProductNames");
    return this.manager.executeQuery(query);
  }

  // Used to load an existing entity from cache
  loadExisting(entityType,id) {
      return {
        entity: this.manager.getEntityByKey(entityType,id),
        entityManager: this.manager
      };
  // });
}

  // Used to create a new entity
  createNew(type) {
      console.log(type);
      return {
        entity: this.manager.createEntity(type),
        entityManager: this.manager
      };
    };

}
